version: "3"
services:
  db:
    # replace username/repo:tag with your name and image details
    image: db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - webnet
  api:
    # replace username/repo:tag with your name and image details
    image: api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 750M
      restart_policy:
        condition: on-failure
    #volumes:
    #  - /TestReporter/api:/app
    ports:
      - "1111:1111"
    networks:
      - webnet
networks:
  webnet: