version: "3"
services:
  db:
    # replace username/repo:tag with your name and image details
    image: tr-db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 550M
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - webnet
  api:
    # replace username/repo:tag with your name and image details
    image: tr-api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2150M
      restart_policy:
        condition: on-failure
    #volumes:
    #  - /TestReporter/api:/app
    ports:
      - "1111:1111"
    networks:
      - webnet
    depends_on:
      - db
  front:
    # replace username/repo:tag with your name and image details
    image: tr-fr
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 750M
      restart_policy:
        condition: on-failure
    ports:
      - "8083:80"
    networks:
      - webnet
    depends_on:
      - api
networks:
  webnet: